/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as GaleriaRouteImport } from './routes/galeria'
import { Route as NosotrosRouteImport } from './routes/nosotros'
import { Route as TerminosRouteImport } from './routes/terminos'
import { Route as VuelosRouteImport } from './routes/vuelos'
import { Route as ApiPublicClipWebhookRouteImport } from './routes/api/public/clip-webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const GaleriaRoute = GaleriaRouteImport.update({
  id: '/galeria',
  path: '/galeria',
  getParentRoute: () => rootRouteImport,
} as any)
const NosotrosRoute = NosotrosRouteImport.update({
  id: '/nosotros',
  path: '/nosotros',
  getParentRoute: () => rootRouteImport,
} as any)
const TerminosRoute = TerminosRouteImport.update({
  id: '/terminos',
  path: '/terminos',
  getParentRoute: () => rootRouteImport,
} as any)
const VuelosRoute = VuelosRouteImport.update({
  id: '/vuelos',
  path: '/vuelos',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicClipWebhookRoute = ApiPublicClipWebhookRouteImport.update({
  id: '/api/public/clip-webhook',
  path: '/api/public/clip-webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/contacto': typeof ContactoRoute
  '/galeria': typeof GaleriaRoute
  '/nosotros': typeof NosotrosRoute
  '/terminos': typeof TerminosRoute
  '/vuelos': typeof VuelosRoute
  '/api/public/clip-webhook': typeof ApiPublicClipWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/contacto': typeof ContactoRoute
  '/galeria': typeof GaleriaRoute
  '/nosotros': typeof NosotrosRoute
  '/terminos': typeof TerminosRoute
  '/vuelos': typeof VuelosRoute
  '/api/public/clip-webhook': typeof ApiPublicClipWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/contacto': typeof ContactoRoute
  '/galeria': typeof GaleriaRoute
  '/nosotros': typeof NosotrosRoute
  '/terminos': typeof TerminosRoute
  '/vuelos': typeof VuelosRoute
  '/api/public/clip-webhook': typeof ApiPublicClipWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/checkout'
    | '/contacto'
    | '/galeria'
    | '/nosotros'
    | '/terminos'
    | '/vuelos'
    | '/api/public/clip-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkout'
    | '/contacto'
    | '/galeria'
    | '/nosotros'
    | '/terminos'
    | '/vuelos'
    | '/api/public/clip-webhook'
  id:
    | '__root__'
    | '/'
    | '/checkout'
    | '/contacto'
    | '/galeria'
    | '/nosotros'
    | '/terminos'
    | '/vuelos'
    | '/api/public/clip-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactoRoute: typeof ContactoRoute
  GaleriaRoute: typeof GaleriaRoute
  NosotrosRoute: typeof NosotrosRoute
  TerminosRoute: typeof TerminosRoute
  VuelosRoute: typeof VuelosRoute
  ApiPublicClipWebhookRoute: typeof ApiPublicClipWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galeria': {
      id: '/galeria'
      path: '/galeria'
      fullPath: '/galeria'
      preLoaderRoute: typeof GaleriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nosotros': {
      id: '/nosotros'
      path: '/nosotros'
      fullPath: '/nosotros'
      preLoaderRoute: typeof NosotrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terminos': {
      id: '/terminos'
      path: '/terminos'
      fullPath: '/terminos'
      preLoaderRoute: typeof TerminosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vuelos': {
      id: '/vuelos'
      path: '/vuelos'
      fullPath: '/vuelos'
      preLoaderRoute: typeof VuelosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/clip-webhook': {
      id: '/api/public/clip-webhook'
      path: '/api/public/clip-webhook'
      fullPath: '/api/public/clip-webhook'
      preLoaderRoute: typeof ApiPublicClipWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckoutRoute: CheckoutRoute,
  ContactoRoute: ContactoRoute,
  GaleriaRoute: GaleriaRoute,
  NosotrosRoute: NosotrosRoute,
  TerminosRoute: TerminosRoute,
  VuelosRoute: VuelosRoute,
  ApiPublicClipWebhookRoute: ApiPublicClipWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
