/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GaleriaRouteImport } from './routes/galeria'
import { Route as NosotrosRouteImport } from './routes/nosotros'
import { Route as TerminosRouteImport } from './routes/terminos'
import { Route as VuelosRouteImport } from './routes/vuelos'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GaleriaRoute = GaleriaRouteImport.update({
  id: '/galeria',
  path: '/galeria',
  getParentRoute: () => rootRouteImport,
} as any)
const NosotrosRoute = NosotrosRouteImport.update({
  id: '/nosotros',
  path: '/nosotros',
  getParentRoute: () => rootRouteImport,
} as any)
const TerminosRoute = TerminosRouteImport.update({
  id: '/terminos',
  path: '/terminos',
  getParentRoute: () => rootRouteImport,
} as any)
const VuelosRoute = VuelosRouteImport.update({
  id: '/vuelos',
  path: '/vuelos',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/galeria': typeof GaleriaRoute
  '/nosotros': typeof NosotrosRoute
  '/terminos': typeof TerminosRoute
  '/vuelos': typeof VuelosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/galeria': typeof GaleriaRoute
  '/nosotros': typeof NosotrosRoute
  '/terminos': typeof TerminosRoute
  '/vuelos': typeof VuelosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/galeria': typeof GaleriaRoute
  '/nosotros': typeof NosotrosRoute
  '/terminos': typeof TerminosRoute
  '/vuelos': typeof VuelosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/galeria' | '/nosotros' | '/terminos' | '/vuelos'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/galeria' | '/nosotros' | '/terminos' | '/vuelos'
  id: '__root__' | '/' | '/galeria' | '/nosotros' | '/terminos' | '/vuelos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GaleriaRoute: typeof GaleriaRoute
  NosotrosRoute: typeof NosotrosRoute
  TerminosRoute: typeof TerminosRoute
  VuelosRoute: typeof VuelosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galeria': {
      id: '/galeria'
      path: '/galeria'
      fullPath: '/galeria'
      preLoaderRoute: typeof GaleriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nosotros': {
      id: '/nosotros'
      path: '/nosotros'
      fullPath: '/nosotros'
      preLoaderRoute: typeof NosotrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terminos': {
      id: '/terminos'
      path: '/terminos'
      fullPath: '/terminos'
      preLoaderRoute: typeof TerminosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vuelos': {
      id: '/vuelos'
      path: '/vuelos'
      fullPath: '/vuelos'
      preLoaderRoute: typeof VuelosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GaleriaRoute: GaleriaRoute,
  NosotrosRoute: NosotrosRoute,
  TerminosRoute: TerminosRoute,
  VuelosRoute: VuelosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
